### PR TITLE
File structure reorganized and Grunt file updated. 

### PR DESCRIPTION
**Pull request by treecasiano**
I moved all the compiled assets, third-party libraries, and index.html into a dist folder and approriate sub-folders. I pulled the sass files and ui, app, and api JavaScript files into a src folder. Gruntfile.js has been updated to reflect the new locations.

### CODE REVIEW

**Comment by jimtyhurst** [comment]
This is good in separating out the 3rd-party code, but that should not be in the dist directory, which should get re-built every time there is a build. The idea is for the gruntfile to reference all the source, including all the assets, images, code, 3rd party libraries, config files, etc. and bring them together into the dist directory, while doing any building that has to happen along the way, such as compiling sass files, concatenating, obfuscating, and minifying JavaScript files, putting img files into sprite files, ... whatever we decide is relevant to our build. I cannot give more concrete suggestions right now, but I will look at this again tomorrow to give more specific suggestions of how that should work.

**Comment by treecasiano** [comment]
@jimtyhurst Thanks for the review. I understand what you mean and will revise after I do a little more research tomorrow.

**Comment by treecasiano** [comment]
I'm going to close the PR for now and will revisit this task at our next meeting.

**Comment by treecasiano** [comment]
I added the grunt-contrib-copy module and edited the grunt file so that index.html and the libs folder are copied into the dist folder.

**Comment by treecasiano** [comment]
I'm closing this pull request. Pull request #22 is a better process and makes the dist folder completely disposable.

**Pull request closed without merging**
